version: '3'

services:
    nginx-trello:
        container_name: nginx-trello
        build: ./docker/web/
        ports:
            - '800:88'
        volumes:
            - ./app/:/var/www/
            - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
        links:
            - app-trello

    app-trello:
        container_name: app-trello
        build: ./docker/php/
        command: /sbin/init
        privileged: true
        restart: always
        expose:
            - "9000"
        links:
            - db-trello
        volumes:
            - ./app/:/var/www/
            - ./docker/php/php.ini:/etc/php/7.4/fpm/php.ini
            - ./docker/php/www.conf:/etc/php/7.4/fpm/pool.d/www.conf

    db-trello:
        image: mysql:8.0
        container_name: db-trello
        environment:
            MYSQL_DATABASE: db-so-trello
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        ports:
        - "3306:3306"
        volumes:
        - ./docker/db/data:/var/lib/mysql
        - ./docker/db/sql:/docker-entrypoint-initdb.d

# networks:
#     app_net:
#         driver: bridge
#         ipam:
#             config:
#             - subnet: 172.0.11.0/24
